### ISSUE TITLE
使用反馈

### ISSUE THREAD

**Issue by Protamandua** [troyeguo/coodo-pay#1]
很棒的项目，非常感谢作者提供这样好的开源项目和详尽的教程，帮了很大的忙。
在使用中遇到一些小问题：
1/ 替换Vaptcha验证ID后，可以正常加载验证码，但使用订单号查询和邮箱查询均无法查询到结果（支付与否均提示未查询到订单信息）；
2/ 邮箱似乎不能正常发件；
3/ heroku的速度确实不够理想，才疏学浅使用宝塔部署到linux没有成功，如能有这方面的详细教程，不胜感激；

👍

**Comment by troyeguo** [comment]
感谢您的反馈！
1/ 订单查询和邮箱查询，在我这里可以正常使用的，您可以在后台管理系统的订单管理中看看可不可以查到您的订单
2/ 邮件发送功能确实有问题，我会尽快修复的
3/ 其实在heroku绑定了托管在cloudflare的域名之后，速度还行的，可能晚上延迟会有点高，我最近又更新了一个版本把商品页的加载速度降低到了3s以内，您可以看看速度有没有提升，我没用宝塔部署过，直接部署到Linux的教程你可以看看这个：https://blog.csdn.net/xiamocsdn/article/details/100535519
如果您在使用过程中遇到了其他问题，欢迎随时与我取得联系

**Comment by Protamandua** [comment]
非常感谢您的耐心回复，已升级新版本，加载速度有显著提升！👍
订单查询和邮箱查询在后台可以查询到，产品支付界面支付后可以查询，清除cookie之后就无法查询到，新版本中使用隐身模式复现该情况，截图供您参考。
![image](https://user-images.githubusercontent.com/9107773/87541376-bbd63c00-c6d3-11ea-85b8-3455e6f2a762.png)
![image](https://user-images.githubusercontent.com/9107773/87541433-d5778380-c6d3-11ea-8afb-583f828cdbad.png)

**Comment by troyeguo** [comment]
感谢您的反馈！

1/ 订单查询的bug已经修复了
2/  邮件在付款完成之后才会发送，qq邮箱发送可能会有一定的延迟，一般不会超过一天，你可以在qq邮箱->已发送-> 查询发信投递状态，查看邮件发送情况

如果您在使用过程遇到任何问题，欢迎随时与我取得联系
