### ISSUE TITLE
统计数据加载问题

### ISSUE THREAD

**Issue by Protamandua** [troyeguo/coodo-pay#2]
您好，已成功部署linux，非常感谢。
目前遇到的问题即新版本中数据统计一直处于加载中（linux和heroku下情况相同），在v1.2.0正常。
![image](https://user-images.githubusercontent.com/9107773/87770619-d46c6080-c851-11ea-965a-b7c67f5b9e8d.png)

**Comment by troyeguo** [comment]
您好，会不会是网络问题，可以多刷新看看。

**Comment by troyeguo** [comment]
不好意思，已经定位到这个bug，刚才又更新了一版，您看看现在还有这个问题吗？

**Comment by Protamandua** [comment]
谢谢！新版本Linux部署成功，数据统计正常。
