### ISSUE TITLE
忘记密码答案如何重置？

### ISSUE THREAD

**Issue by yingapp** [troyeguo/coodo-pay#4]

**Comment by troyeguo** [comment]
您好！
如果您忘了登陆密码，可以在登陆页面点击忘记密码，进行重置，如果忘了密保问题的答案，可以去MongoDB Altas 您创建的数据库中的 collection -> users 查看密保问题的答案。
https://i.loli.net/2020/09/17/B2pqUiIMw5P6HnZ.png
https://i.loli.net/2020/09/17/OXamn53h7RSLpoB.png

**Comment by yingapp** [comment]
我换了一个MongoDB Altas 账号，以前的忘记密码了，邮箱收不到MongoDB Altas 的忘记密码email。
新的MongoDB Altas 里面没有User。
![屏幕截图 2020-09-21 081001](https://user-images.githubusercontent.com/47973401/93725491-50807d00-fbe2-11ea-8871-66fce1a02c7a.png)

**Comment by troyeguo** [comment]
如果您无法登录之前的Mongodb altas账号，那就只能使用新账号的新数据库链接重新部署，没有user是因为，这个数据库您还没有注册您的账号，您可以将这个数据库链接填写到配置项中重新部署，按照之前的方法，重新填写密保问题。

**Comment by yingapp** [comment]
已经重新配置了，log里面也显示连接成功，但输入http://localhost:port/#/install以后就跳转到http://localhost:port/#/login，好像使用的以前的mongoDB，但config.js里面已经改成了新的mongDB连接，:(

**Comment by yingapp** [comment]
![Uploading 屏幕截图 2020-09-21 170843.png…]()

**Comment by yingapp** [comment]
![屏幕截图 2020-09-21 170843](https://user-images.githubusercontent.com/47973401/93749888-4768cd80-fc2d-11ea-85b1-989b555c4b88.png)

**Comment by yingapp** [comment]
https://i.loli.net/2020/09/21/eWHfdVRCXLy1Zpo.png

**Comment by troyeguo** [comment]
如果总是自动跳转login页面，就表明您之前成功登录过，您可以看一下setting里的isFirst属性是不是no，这种情况您可以点击setting旁边的删除按钮，把它给删掉，重新尝试注册。
https://i.loli.net/2020/09/21/ZpViPAW85cd1v2H.png

**Comment by yingapp** [comment]
删掉重启后又添加了settings，且强制跳转到login
https://i.loli.net/2020/09/22/X9WnVbjEMxGLg4K.png

**Comment by troyeguo** [comment]
您可以尝试升级到最新的1.5版本，然后开启浏览器匿名访问模式，或者清空缓存，再次尝试，我这里重复了，是没有问题的
